name: alloc
on:
  workflow_dispatch:

jobs:
  alloc:
    environment: send

    permissions:
      contents: "read"
      id-token: "write"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0"
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - name: Send dummy file to Google drive
        id: send
        uses: hankei6km/gdrive-act-send@v0.2.0
        with:
          parent_id: ${{ secrets.PARENT_ID }}
          dest_file_name: ${{ secrets.DEST_FILE_NAME }}
          src_file_name: blank.pdf
          # サービスアカウントから一般アカウントの transfer_ownership は Google の mimeType が必要.
          dest_mime_type: application/pdf
          src_mime_type: text/plain

      - name: Share anyone
        uses: hankei6km/gdrive-act-share@v0.1.1
        with:
          file_id: ${{ steps.send.outputs.file_id }}
          type: anyone
          role: reader
